import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "./providers";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// Define the Geist font variable
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // To avoid hydration issues, ensure consistent class names between SSR and CSR
  const isClient = typeof window !== "undefined";

  return (
    <html lang="en" className={isClient ? geist.variable : "default-font-class"}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"

        >
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}

